<!-- LOADES LIGHT / DARK MODE : IMPORTANT -->
<script type ="text/JavaScript">
           initFunction();
</script>

<!-- HEADER - CONTAINS: LOGO + HEADING + MODE BUTTON-->
<div class="bg_color0" id="eater" style="width:100%; height:250px; position:fixed; transition:background 0.5s ease, background-position-y 0s ease; background-position-y: 0px"> </div>
<header  class="bg_color1 full_display shadow_s" id="top_header" style="width:100%;position:fixed;top:0px;left:0px;">
       
        <a href="index.php" target="_self" id= "homepage_logo" style="padding:1px"> 
          <svg width="66.703598mm" height="66.703598mm" viewBox="0 0 66.703598 66.703598" style="width:inherit; height:auto;">
         
           <g transform="translate(-62.276131,-45.64518)">
            <rect class="bg_color8" y="45.64518" x="62.276131" height="66.703598" width="66.703598" />
            <g>
              <path class="bg_color9" d="m 90.695266,55.04993 -2.889357,10.4345 -1.592587,0.0129 -0.725223,-5.71076 -1.763509,8.41344 -0.573115,7.76541 1.078568,0.86713 -2.147867,27.16993 h 2.333707 c 0,0 0.674726,-7.34169 3.211093,-7.37888 2.530872,0.0372 2.121915,7.37888 2.121915,7.37888 h 2.333707 l 1.86261,-27.16993 1.206568,-0.86713 0.573115,-7.76541 -0.521626,-8.41344 -1.567656,5.71076 -1.591199,-0.0129 z"
                 />
              <g transform="matrix(0.81528563,0,-0.09052499,1.226564,0,0)">
                <path class="bg_color9" d="m 128.62622,69.704167 h 10.4052 V 83.30268 q -1.04052,0.34086 -2.09898,0.6279 -1.05846,0.2691 -2.20662,0.466439 -1.13022,0.1794 -2.38602,0.28704 -1.23786,0.10764 -2.63718,0.10764 -2.94216,0 -5.22054,-0.861119 -2.26044,-0.87906 -3.82121,-2.583359 -1.54284,-1.722239 -2.35014,-4.233838 -0.8073,-2.529538 -0.8073,-5.830496 0,-3.085679 0.897,-5.579337 0.897,-2.493659 2.63718,-4.233838 1.75811,-1.758119 4.30559,-2.690999 2.56542,-0.950819 5.86638,-0.950819 2.09898,0 4.10826,0.448499 2.00928,0.4485 3.6777,1.1661 l -1.84782,4.449117 q -1.21992,-0.609959 -2.76276,-1.022579 -1.5249,-0.41262 -3.21126,-0.41262 -1.82988,0 -3.30096,0.64584 -1.45314,0.6279 -2.49366,1.793999 -1.04052,1.166099 -1.59666,2.816578 -0.55614,1.65048 -0.55614,3.677698 0,1.937519 0.37674,3.552119 0.39468,1.596659 1.21992,2.762758 0.82524,1.166099 2.11692,1.811939 1.30962,0.64584 3.12156,0.64584 1.18404,0 1.99134,-0.10764 0.82524,-0.10764 1.54284,-0.25116 v -5.471697 h -4.96938 z" />
              </g>
            </g>
            <path class="bg_color10" d="m 91.224428,54.52074 -2.889357,10.4345 -1.592587,0.0129 -0.725223,-5.71076 -1.763509,8.41344 -0.573115,7.76541 1.078568,0.86713 -2.147867,27.16993 h 2.333707 c 0,0 0.674726,-7.34169 3.211093,-7.37888 2.530872,0.0372 2.121915,7.37888 2.121915,7.37888 h 2.333707 l 1.86261,-27.16993 1.206568,-0.86713 0.573115,-7.76541 -0.521626,-8.41344 -1.567656,5.71076 -1.591199,-0.0129 z"
               />
            <g transform="matrix(0.81528563,0,-0.09052499,1.226564,0,0)">
              <path class="bg_color10" d="m 129.22737,69.272725 h 10.4052 v 13.598513 q -1.04052,0.34086 -2.09898,0.627899 -1.05846,0.2691 -2.20662,0.46644 -1.13022,0.1794 -2.38602,0.28704 -1.23786,0.10764 -2.63718,0.10764 -2.94216,0 -5.22054,-0.86112 -2.26043,-0.879059 -3.82121,-2.583358 -1.54284,-1.722239 -2.35014,-4.233838 -0.8073,-2.529539 -0.8073,-5.830497 0,-3.085678 0.897,-5.579337 0.897,-2.493658 2.63718,-4.233837 1.75811,-1.75812 4.30559,-2.690999 2.56542,-0.95082 5.86638,-0.95082 2.09898,0 4.10826,0.4485 2.00928,0.4485 3.6777,1.1661 l -1.84782,4.449117 q -1.21992,-0.609959 -2.76276,-1.022579 -1.5249,-0.41262 -3.21126,-0.41262 -1.82988,0 -3.30096,0.64584 -1.45314,0.627899 -2.49366,1.793999 -1.04052,1.166099 -1.59666,2.816578 -0.55614,1.650479 -0.55614,3.677698 0,1.937519 0.37674,3.552118 0.39468,1.596659 1.21992,2.762759 0.82524,1.166099 2.11692,1.811939 1.30962,0.64584 3.12156,0.64584 1.18404,0 1.99134,-0.10764 0.82524,-0.10764 1.54284,-0.25116 v -5.471697 h -4.96938 z" 
                />
              </g>
           </g>
          
         </svg>
        </a>
       
        <a class="color0" id="heading" href="index.php" target="_self" style="text-decoration:none; float:left;"><h1>Knihovna Gymnázia Klatovy</h1></a>
       
        <div id="darkMode_div" style="position:absolute; right:125px; margin:5px;  ">
            <button id="button_darkMode" style="opacity:0;float:left" onClick="switchMode();" > </button>
            <label class="color1" id="label_darkMode_text" style="float:left; position:relative; cursor:pointer" for="button_darkMode" > 
               Tmavý režim:
            </label>
            <label style="float:left; position:relative; margin-left:5px; cursor:pointer" for="button_darkMode">
              <div style="position:absolute; top:0.4em" >
                <span id="label_darkMode_buttonBc" style="position:absolute; top:-1px; left:4px; width:30px; height:7px; display:block; border: solid 2px var(--bg-color-1-l); transition: all .5s ease;"></span>
                <span id="label_darkMode_buttonKnob" style="position:absolute; top:-7px; width:19px; height:18px; display:block; border: solid 2px var(--bg-color-1-l); transition: all .1s ease;"></span>
              </div>
            </label>
        </div>
        
</header>

<!-- MAIN BODY DIV - CONTAINS: ALL CONTENT -->
<div class="normal_position" id="main_content" style="padding:8px; padding-top: 240px; min-height:500px">
  
  <!-- SEARCH WINDOW DIV - CONTAINS: SEARCH BAR-->
  <div  style="min-height:160px;">
    <div class="bg_color2 min_w shadow_se" id="search_window" style="padding:34px;">
        
        <form id = "search_form" method="post" action="request.php">
          
          <label class="color2" for="search_bar" style="margin-bottom:-10px; cursor:text; font-weight:bold; display:block;"> 
            Hledání knih 
          </label> 
          <br />
          
          <input class="bg_color3 color3" id="search_bar" style="width:80%; border-style:solid; padding:5px; line-height: 1.5em;" type="text" name="search_book" placeholder="název, autor..." >
          <button class="bg_color4" id="search_button" style="float:right; width:15%; max-width:130px; margin:0px; height:34px;  margin-left:10px; margin-top:0px;  border-style: solid; border-width: 1px; border-color: #7d7d7d; cursor: pointer" type="submit" name="search_book_submit" form="search_form"> 
            <!-- to button add formmethod POST  ? -->
              <svg id="search_icon" style="height:20px; width:20px;">
                  <line x1="13" y1="13" x2="20" y2="20" stroke="inherit" stroke-width="2" />
                  <circle cx="8" cy="8" r="6" stroke="inherit" stroke-width="2" fill="none" />
              </svg>
          </button>
          
        </form>
        
    </div>
  </div>
  
  <script type ="text/JavaScript">
           updateElements();
  </script>
  
  <!--  RESULTS -->
    <div class="bg_color5 hidden min_w shadow_se" id="search_results" >
        <?php
        if (!empty($this->found_books) && is_array($this->found_books)) { ?>
            <table class="color5" id="search_table" cellpadding = "5" cellspacing = "5" >
                <tr class="bg_color5 color4">
                    <th style="width: 25%;" >Název</th>
                    <th style="width: 25%;" >Jméno Autora</th>
                    <th style="width:10%; text-align:center">Sekce</th>
                    <th style="width:10%; text-align:right">Umístění</th>
                    <th style="width:10%; text-align:right; width:10%">Inv. číslo</th>
                    <th style="width:10%; text-align:right">Rok</th>
                    <th colspan="2" style="width:10%; text-align:center">Cena</th>   
                </tr>
                <?php 
                $color_mod = 0;
                foreach ($this->found_books as $book) {
	                $make_space = true;
	                $last_letter = substr($book["author_first_name"], -1);
                    if ($last_letter == "-")
	                    $make_space = false; 
                    
                    if ( $color_mod == 0 ) $color_mod = 1;
                    else $color_mod = 0;
                    
                    if( $color_mod == 1 ) {
                    ?>
                    <tr class="bg_color6">
                    <?php } else { ?>
                    <tr class="bg_color5">
                    <?php } ?>
                    
                        <td style="width:25%;"><?= $book["name"] . (empty($book["name_2"]) ? "" : " | " . $book["name_2"]) ?></td>
                        <td style="width:25%;"><?= $book["author_first_name"] . ($make_space ? " " : "") . $book["author_surname"]?></td>
                        <td style="width:10%; text-align:center"><?= $book["section"] ?></td>
                        <td style="width:10%; text-align:right"><?= $book["location"] ?></td>
                        <td style="width:10%; text-align:right"><?= $book["record_number"] ?></td>
                        <td style="width:10%; text-align:right"><?= $book["year"] ?></td>
                        <td style="width:6%; text-align:right"><?= $book["price"] ?> </td>
                        <td style="width:4%"></td>
                    </tr>
                <?php } ?>  
            </table>
            
            <script>  showResults(); </script>
            
        <?php } elseif (empty($this->found_books)) { ?>
            <p class="color5">Žádné výsledky</p> <!-- TODO highlight this text -->
            
            <script>  showResults(); </script>
            
        <?php } elseif ($this->found_books == "empty_entry") { ?>
            <p class="color5">Zadejte název knihy</p> <!-- TODO highlight this text -->

            <script>  showResults(); </script>

        <?php }  ?>
    </div>
    
</div>

<!-- FOOTER - CONTAINS: CONTACTS (TBA) -->
<footer class="bg_color7 min_w" style="width:100%;min-width: 700px; min-height:100px;padding-top:20px;">
  
  <div class="color6" style="width:fit-content; margin:auto;">   
      <div class="section">
        Vývoj <br />
        <span class="color7"> Jakub Jankovec <br /> Marek Seltenhofer </span>
      </div>
       
      <div class="section">
        Administrace <br />
        <span class="color7"> Mgr. Pavel Hladký </span>
      </div>
   
      <div class="section" style="width:130px">
        SPEF <br />
        <span class="color7"> SPEF </span>
      </div>
   
      <div class="section" style="width:140px">
        Git <br />
        <span class="color7"> 
        <a href="https://www.github.com/mselten/gymkt_library" target="_blank" > 
          github.com 
        </a> 
        </span>
      </div>
  </div>
      
</footer>



