<!-- LOADES LIGHT / DARK MODE : IMPORTANT -->
<script type ="text/JavaScript">
           initFunction();
</script>

<!-- HEADER - CONTAINS: LOGO + HEADING + MODE BUTTON-->
<header id="top_header" class="bg_color1 full_display" style="width:100%;position:fixed;top:0px;left:0px;box-shadow:0px 3px 1px #000;">
   
        <a href="index.php" target="_self" id= "homepage_logo"> <img class="logo" alt="Homepage Logo"> </a>
        <a class="color0" id="heading" href="index.php" target:"_self" style="text-decoration:none; padding-left:8px; float:left; margin-left:40px;"><h1>Knihovna Gymnázia Klatovy</h1></a>
       
        <div style="position:absolute; right:125px; bottom:25px; margin:5px;  ">
            <button style="opacity:0;float:left" id="button_darkMode" onClick="switchMode();" > </button>
            <label class="color1" id="label_darkMode_text" style="float:left; position:relative; cursor:pointer" for="button_darkMode" > 
               Temný režim:
            </label>
            <label style="float:left; position:relative; margin-left:5px; cursor:pointer" for="button_darkMode">
              <div style="position:absolute; top:0.4em" >
                <span id="label_darkMode_buttonBc" style="position:absolute; top:-1px; left:4px; width:30px; height:7px; display:block; border: solid 2px white; transition: all .5s ease;"></span>
                <span id="label_darkMode_buttonKnob" style="position:absolute; top:-7px; width:19px; height:18px; display:block; border: solid 2px white; transition: all .1s ease;"></span>
              </div>
            </label>
        </div>
        
</header>

<!-- MAIN BODY DIV - CONTAINS: ALL CONTENT -->
<div id="main_content" style="padding:8px; padding-top:130px;min-height:500px">
  
  <!-- SEARCH WINDOW DIV - CONTAINS: SEARCH BAR-->
  <div class="bg_color2 min_w" id="search_window" style="margin:auto; margin-top:150px; padding:34px; width:50%">
      
      <form id = "search_form" method="post" action="request.php">
        
        <label class="color2" for="search_bar" style="cursor:text; font-weight:bold; display:block; margin-bottom:-15px;"> Hledání knih </label> <br />
        
        <input class="bg_color3 color3" id="search_bar" type="text" name="search_book" placeholder="název, autor..." style="margin-top:5px; width:80%; border-style:solid; padding:5px; line-height: 1.5em;">
        <button class="bg_color4" id="search_button" type="submit" name="search_book_submit" style="float:right; width:15%; max-width:130px; margin:0px; height:34px;  margin-left:10px; margin-top:5px;  border-style:solid; border-width:1px; border-color:#7d7d7d; cursor:pointer" form="search_form"> 
          <!-- to button add formmethod POST  ? -->
            <svg id="search_icon" style="height:20px; width:20px;">
                <line x1="13" y1="13" x2="20" y2="20" stroke="inherit" stroke-width="2" />
                <circle cx="8" cy="8" r="6" stroke="inherit" stroke-width="2" fill="none" />
            </svg>
        </button>
        
      </form>
      
  </div>
  
  <!--  RESULTS -->
    <div class="bg_color5 hidden min_w" id="search_results" >
        <?php
        if (!empty($this->found_books) && is_array($this->found_books)) { ?>
            <table class="color5" id="search_table" cellpadding = "5" cellspacing = "5" >
                <tr class="bg_color5 color4">
                    <th style="width: 25%;" >Název</th>
                    <th style="width: 25%;" >Jméno Autora</th>
                    <th style="width:10%; text-align:center">Sekce</th>
                    <th style="width:10%; text-align:right">Umístění</th>
                    <th style="width:10%; text-align:right; width:10%">Inv. číslo</th>
                    <th style="width:10%; text-align:right">Rok</th>
                    <th colspan="2" style="width:10%; text-align:center">Cena</th>   
                </tr>
                <?php 
                $color_mod = 0;
                foreach ($this->found_books as $book) {
	                $make_space = true;
	                $last_letter = substr($book["author_first_name"], -1);
                    if ($last_letter == "-")
	                    $make_space = false; 
                    
                    if ( $color_mod == 0 ) $color_mod = 1;
                    else $color_mod = 0;
                    
                    if( $color_mod == 1 ) {
                    ?>
                    <tr class="bg_color6">
                    <?php } else { ?>
                    <tr class="bg_color5">
                    <?php } ?>
                    
                        <td style="width:25%;"><?= $book["name"] . (empty($book["name_2"]) ? "" : " | " . $book["name_2"]) ?></td>
                        <td style="width:25%;"><?= $book["author_first_name"] . ($make_space ? " " : "") . $book["author_surname"]?></td>
                        <td style="width:10%; text-align:center"><?= $book["section"] ?></td>
                        <td style="width:10%; text-align:right"><?= $book["location"] ?></td>
                        <td style="width:10%; text-align:right"><?= $book["record_number"] ?></td>
                        <td style="width:10%; text-align:right"><?= $book["year"] ?></td>
                        <td style="width:6%; text-align:right"><?= $book["price"] ?> </td>
                        <td style="width:4%"></td>
                    </tr>
                <?php } ?>  
            </table>
            
            <script>  showResults(); </script>
            
        <?php } elseif (empty($this->found_books)) { ?>
            <p class="color1">Žádné výsledky</p> <!-- TODO highlight this text -->
            
            <script>  showResults(); </script>
            
        <?php } elseif ($this->found_books == "empty_entry") { ?>
            <p class="color1">Zadejte název knihy</p> <!-- TODO highlight this text -->

            <script>  showResults(); </script>

        <?php }  ?>
    </div>

</div>

<!-- FOOTER - CONTAINS: CONTACTS (TBA) -->
<footer class="bg_color7 min_w" style="width:100%;min-width: 700px; min-height:100px;padding-top:20px; padding-bottom:20px">
  
  <table class="color7" style="padding:30px; margin:auto; width:70%; border-collapse:collapse; font-weight:100" cellpadding = "5" cellspacing = "5" >
     <tr class="color6" style="text-align:center">
        <th style="width:25%; text-align:left">Vývoj </th>
        <th style="width:25%"> Administrace </th>
        <th style="width:25%"> SPEF </th>
        <th style="width:25%; text-align:right"> Git </th>
     </tr>
     <tr style="text-align:center">
        <td style="text-align:left"> Jakub Jankovec </td>
        <td> Mgr. Pavel Hladký </th>
        <td> SPEF </td>
        <td style="text-align:right"> github.com/mselten/gymkt_library</td>
     </tr>
     <tr style="text-align:left">
       <td> Marek Seltenhofer </td>
     </tr>
  </table>
      
</footer>



