<!-- LOADES LIGHT / DARK MODE : IMPORTANT -->
<script type ="text/JavaScript">
           initFunction();
</script>

<!-- HEADER - CONTAINS: LOGO + HEADING + MODE BUTTON-->
<header class="bg_color1" style="width:100%;min-height:110px;padding:30px;position:fixed;top:0px;left:0px;box-shadow:0px 1px 1px #000;">
   
        <a href="index.php" target="_self" id= "homepage_logo"> <img class="logo" alt="Homepage Logo"> </a>
        <a class="color0" id="heading" href="index.php" target:"_self" style="text-decoration:none; padding-left:8px; float:left; margin-top:50px"> Best Heading ever mk 2 </a>
       
        <div style="position:absolute; right:125px; bottom:25px; margin:5px;  ">
            <button style="opacity:0;float:left" id="button_darkMode" onClick="switchMode();" > </button>
            <label class="color1" id="label_darkMode_text" style="float:left; position:relative; cursor:pointer" for="button_darkMode" > 
               Dark mode:
            </label>
            <label style="float:left; position:relative; margin-left:5px; cursor:pointer" for="button_darkMode">
              <div style="position:absolute; top:0.59em" >
                <span id="label_darkMode_buttonBc" style="position:absolute; top:-1px; left:4px; width:30px; height:7px; display:block; border: solid 2px white; transition: all .5s ease;"></span>
                <span id="label_darkMode_buttonKnob" style="position:absolute; top:-7px; width:19px; height:18px; display:block; border: solid 2px white; transition: all .1s ease;"></span>
              </div>
            </label>
        </div>
        
</header>

<!-- MAIN BODY DIV - CONTAINS: ALL CONTENT -->
<div id="main_content" style="padding:8px; padding-top:130px;min-height:500px">
  
  <!-- SEARCH WINDOW DIV - CONTAINS: SEARCH BAR-->
  <div class="bg_color1" id="search_window" style="margin:auto; margin-top:150px; padding:34px; min-width:500px; width:50%">
      
      <form id = "search_form" method="post" action="request.php">
        
        <label class="color1" for="search_bar" style="cursor:text"> Best search bar ever... such search... much wow </label> <br />
        
        <input class="bg_color2 color0" id="search_bar" type="text" name="search_book" placeholder="Type plz" style="margin-top:5px; width:80%; border-style:solid; padding:5px; line-height: 1.5em;">
        <button class="bg_color3" id="search_button" type="submit" name="search_book_submit" style="float:right; width:15%; max-width:130px; margin:0px; height:34px;  margin-left:10px; margin-top:5px;  border-style:solid; border-width:1px; border-color:#7d7d7d; cursor:pointer" form="search_form"> 
          <!-- to button add formmethod POST  ? -->
            <svg id="search_icon" style="height:20px; width:20px;">
                <line x1="13" y1="13" x2="20" y2="20" stroke="#7d7d7d" stroke-width="2" />
                <circle cx="8" cy="8" r="6" stroke="#7d7d7d" stroke-width="2" fill="none" />
            </svg>
        </button>
        
      </form>
      
  </div>
  
  <!--  RESULTS -->
    <div id="search_results">
        <?php
        if (!empty($this->found_books) && is_array($this->found_books)) { ?>
            <table cellpadding = "5" cellspacing = "5" >
                <tr>
                    <th>Název</th>
                    <th>Jméno Autora</th>
                    <th>Sekce</th>
                    <th>Umístění</th>
                    <th>Inv. číslo</th>
                    <th>Rok</th>
                    <th>Cena</th>
                </tr>
                <?php foreach ($this->found_books as $book) {
	                $make_space = true;
	                $last_letter = substr($book["author_first_name"], -1);
                    if ($last_letter == "-")
	                    $make_space = false; ?>

                    <tr>
                        <td><?= $book["name"] . (empty($book["name_2"]) ? "" : " | " . $book["name_2"]) ?></td>
                        <td><?= $book["author_first_name"] . ($make_space ? " " : "") . $book["author_surname"]?></td>
                        <td><?= $book["section"] ?></td>
                        <td><?= $book["location"] ?></td>
                        <td><?= $book["record_number"] ?></td>
                        <td><?= $book["year"] ?></td>
                        <td><?= $book["price"] ?></td>
                    </tr>
                <?php } ?>
            </table>

        <?php } elseif (empty($this->found_books)) { ?>
            <p>Žádné výsledky</p> <!-- TODO highlight this text -->

        <?php } elseif ($this->found_books == "empty_entry") { ?>
            <p>Zadejte název knihy</p> <!-- TODO highlight this text -->

        <?php } ?>
    </div>

</div>

<!-- FOOTER - CONTAINS: CONTACTS (TBA) -->
<footer class="bg_color4" style="width:100%;height:100px;min-width:600px">
  <p style="color:#fff;float:right;padding:8px"> Extra info? </p>      
</footer>



